//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCMS.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class cCar
    {
        public int cId { get; set; }

        [DisplayName("Make")]
        public string cMake { get; set; }

        [DisplayName("Model")]
        public string cModel { get; set; }

        [DisplayName("Year")]
        public int cYear { get; set; }

        [DisplayName("Gear Type")]
        public string cGear { get; set; }

        [DisplayName("Body Type")]
        public string cBody { get; set; }

        [DisplayName("Fuel Type")]
        public string cFuel { get; set; }

        [DisplayName("Door")]
        public string cDoor { get; set; }

        [DisplayName("Color")]
        public string cColor { get; set; }

        [DisplayName("Photo URL")]
        public string cPhoto { get; set; }

        [DisplayName("Mileage")]
        public int cMileage { get; set; }

        [DisplayName("Engine Type")]
        public decimal cEngine { get; set; }
    }
}
