//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCMS.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class cContact
    {
        public int cCId { get; set; }

        [DisplayName("Customer Name")]
        public string cCName { get; set; }

        [DisplayName("Customer Email")]
        [EmailAddress]
        public string cCEmail { get; set; }

        [DisplayName("Contact Type")]
        public string cCType { get; set; }

        [DisplayName("Message")]
        public string cCMessage { get; set; }
    }
}
