//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCMS.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class cModel
    {
        public int cmId { get; set; }

        [DisplayName("Make")]
        public string cmMake { get; set; }

        [DisplayName("Model")]
        public string cmModel { get; set; }
    }
}
