//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCMSEntities : DbContext
    {
        public dbCMSEntities()
            : base("name=dbCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cBody> cBodies { get; set; }
        public virtual DbSet<cCar> cCars { get; set; }
        public virtual DbSet<cFuel> cFuels { get; set; }
        public virtual DbSet<cGear> cGears { get; set; }
        public virtual DbSet<cMake> cMakes { get; set; }
        public virtual DbSet<cAdmin> cAdmins { get; set; }
        public virtual DbSet<cContact> cContacts { get; set; }
        public virtual DbSet<cEngine> cEngines { get; set; }
        public virtual DbSet<cColor> cColors { get; set; }
        public virtual DbSet<cModel> cModels { get; set; }
    }
}
